/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package jpkg

import kotlin.math.*
import kotlin.random.*

class App {
    val greeting = "Hello: " + Random.nextDouble(abs(sin(PI) + cos(PI)))
}

fun main(args: Array<String>) {
    println(App().greeting)
}
